# Generated by Django 5.2.3 on 2025-07-01 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrammarTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "explanation",
                    models.TextField(help_text="Can include HTML for formatting."),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order in which topics are presented."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="VocabularyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("afaan_oromo_word", models.CharField(max_length=200)),
                ("translation_english", models.CharField(max_length=200)),
                (
                    "pronunciation_audio_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("example_sentence_afaan", models.TextField(blank=True, null=True)),
                (
                    "example_sentence_translation",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., greetings, numbers, animals",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["afaan_oromo_word"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_grammar_topics",
                    models.ManyToManyField(
                        blank=True,
                        related_name="completed_by_users",
                        to="learning_modules.grammartopic",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_vocabulary_items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="completed_by_users",
                        to="learning_modules.vocabularyitem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Progress",
            },
        ),
    ]
